### PR TITLE
Add pragma once to every header (allows unity build)

### PR DESCRIPTION
**Pull request by Salamandar**
That's pretty straightforward : Adding `#pragma once` to every header allows unity build (compile all files together to allow better optimization).

### CODE REVIEW

**Comment by E5ten** [comment]
Since `#pragma once` is an extension, it would probably be better to use `#ifndef` guards.

**Comment by michaelforney** [comment]
Yes, samurai is written in ISO C99, so we can't use `#pragma once`. But, I don't think I want to add `#ifndef` guards either.

Are you actually able to detect a difference in performance by compiling all the files together? If so, could you attach the results of your tests?

**Comment by Salamandar** [comment]
> I don't think I want to add #ifndef guards either.
Why ?

> Are you actually able to detect a difference in performance by compiling all the files together? If so, could you attach the results of your tests?

Actually, yesterday I didn't have a big enough bench set, and I was wondering if you had one.

**Comment by michaelforney** [comment]
> > I don't think I want to add #ifndef guards either.
> 
> Why ?

A simple way to prevent the need for include guards is to not include headers in other headers. See the "Include files" section of http://doc.cat-v.org/bell_labs/pikestyle.

> > Are you actually able to detect a difference in performance by compiling all the files together? If so, could you attach the results of your tests?
> 
> Actually, yesterday I didn't have a big enough bench set, and I was wondering if you had one.

I usually just do no-op builds in large projects like chromium or llvm. In any build that runs any commands, samurai's contribution to the build time is lost in the noise.

**Comment by Salamandar** [comment]
Well I just did a benchmark on Gimp, and the difference is small but visible : 
```
no unity: 0.12967142857142855
unity:    0.12873913043478247
```

**Comment by michaelforney** [comment]
What does "count" mean here? Is that the number of samples you ran?

Note that you can build with `LDFLAGS=-flto` to enable LTO, you don't need meson.

**Comment by Salamandar** [comment]
Yes, `count` is the number of samples. I did a much longer run (8000 samples) with the same result.

**Comment by michaelforney** [comment]
Sorry, I'm not interested in supporting a unity build. If you really want to do this, you can just cat the files after removing their `#include "..."` lines, and prepending some initial includes:

```
{ printf '#include <%s>\n' stdio.h; printf '#include "%s"\n' *.h; grep -hv '^#include "' *.c; } | gcc -x c - -o samu
```

**Pull request closed without merging**
